# Generated by Django 3.1.2 on 2020-10-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201012_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'CAT'), ('dog', 'GOD'), ('parrot', 'PARROT')], max_length=6),
        ),
    ]
