# Generated by Django 3.1.2 on 2020-10-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201012_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('parrot', 'parrot')], max_length=6),
        ),
    ]
